name: 3.13 6.1 Run buildout and instance
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            eggs
          key: cache-Py3.13-Plone6.1
      - name: Install venv
        run: |
          pip install virtualenv
          virtualenv -p 3 .
          bin/pip install -r requirements-6.1.txt
          bin/buildout -c test-6.1.x.cfg install instance
      - name: Check that instance starts
        run: |
          bin/instance run startup.py
