name: 3.9 6.0 Run buildout and instance
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9
      - name: Caching
        uses: actions/cache@v3.2.3
        with:
          path: |
            eggs
          key: cache-Py3.9-Plone6.0
      - name: Install venv
        run: |
          pip install virtualenv
          virtualenv -p 3 .
          bin/pip install -r requirements.txt
          bin/buildout -c test-6.x.cfg install instance
      - name: Check that instance starts
        run: |
          bin/instance run startup.py
