name: 2.7 5.2 Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 2.7
      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            eggs
          key: cache-Py2.7-Plone5.2
      - name: Install venv
        run: |
          pip install virtualenv
          virtualenv -p 2 .
          bin/pip install -r requirements.txt
          bin/buildout -c test-5.2.x.cfg install test
      - name: Run unit tests
        run: |
          bin/test
