name: 2.7 5.2 Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: 2.7.18
      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            eggs
          key: cache-Py2.7-Plone5.2
      - name: Install venv
        run: |
          pip install virtualenv
          virtualenv -p 2 .
          bin/pip install -r requirements.txt
          bin/buildout -c test-5.2.x.cfg install test
      - name: Run unit tests
        run: |
          bin/test
